trigger:
- master

name: java-app-to-ado-via-yaml

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildStage
    jobs:
      -  job: BuildJob
         steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'ado-sc'
              mavenPomFile: 'Wallet/pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: '**/*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
              
